# Generated by Django 5.1.6 on 2025-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectApplicatin',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_owner', models.CharField(max_length=100)),
                ('project_owner_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('project_owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('project_implementor', models.CharField(max_length=100)),
                ('implementor_tel', models.CharField(blank=True, max_length=16, null=True)),
                ('implementor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(choices=[('Kirehe', 'Kirehe'), ('Ngoma', 'Ngoma'), ('Kayonza', 'Kayonza'), ('Bugesera', 'Bugesera'), ('Rwamagana', 'Rwamagana'), ('Gatsibo', 'Gatsibo'), ('Nyagatare', 'Nyagatare'), ('Gicumbi', 'Gicumbi'), ('Rulindo', 'Rulindo'), ('Gakenke', 'Gakenke'), ('Musanze', 'Musanze'), ('Burera', 'Burera'), ('Nyabihu', 'Nyabihu'), ('Rubavu', 'Rubavu'), ('Nyamasheke', 'Nyamasheke'), ('Karongi', 'Karongi'), ('Rutsiro', 'Rutsiro'), ('Muhanga', 'Muhanga'), ('Kamonyi', 'Kamonyi'), ('Ruhango', 'Ruhango'), ('Nyanza', 'Nyanza'), ('Gisagara', 'Gisagara'), ('Huye', 'Huye'), ('Nyamagabe', 'Nyamagabe'), ('Ngororero', 'Ngororero'), ('Nyaruguru', 'Nyaruguru'), ('Rusizi', 'Rusizi'), ('Nyarugenge', 'Nyarugenge'), ('Kicukiro', 'Kicukiro'), ('Gasabo', 'Gasabo')], max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('load_capacity_kva', models.FloatField(blank=True, null=True)),
                ('load_capacity_unit', models.CharField(blank=True, choices=[('KW', 'KW'), ('KVA', 'KVA')], max_length=10, null=True)),
                ('tx_capacity_kva', models.FloatField(blank=True, null=True)),
                ('project_category', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('College', 'College'), ('Mining', 'Mining'), ('EV', 'EV'), ('Telecom tower', 'Telecom tower'), ('Broadcasters', 'Broadcasters'), ('Hotels', 'Hotels'), ('Water SS Or TP', 'Water SS Or TP'), ('Health', 'Health'), ('Data Centers', 'Data Centers'), ('Airport', 'Airport'), ('Govt intitution', 'Govt intitution'), ('Street light', 'Street light')], max_length=50, null=True)),
                ('eucl_scope', models.CharField(blank=True, choices=[('Supply&Installation', 'Supply&Installation'), ('Installation', 'Installation'), ('Supervision', 'Supervision')], max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='project_attachments', to='customerPrjcts.projectfile')),
                ('proof_survey_fee_attachments', models.ManyToManyField(blank=True, related_name='proof_survey_fee_files', to='customerPrjcts.projectfile')),
            ],
        ),
    ]
