# Generated by Django 5.1.6 on 2025-03-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerPrjcts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectApplicatin',
            new_name='ProjectApplication',
        ),
    ]
