# Generated by Django 5.1.6 on 2025-04-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerPrjcts', '0002_rename_projectapplicatin_projectapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectapplication',
            old_name='load_capacity_kva',
            new_name='load_capacity',
        ),
    ]
