# Generated by Django 5.1.6 on 2025-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPrjcts', '0003_rename_load_capacity_kva_projectapplication_load_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
